### ISSUE TITLE
Error Taller5 - CoppeliaSim y Python (segunda parte).ipynb

### ISSUE THREAD

**Issue by cabustillo13** [cmoralesd/robopy#1]
Hola @cmoralesd .
He estado viendo tu canal de robótica con Python.

Descubrí que te falto definir los joint1, joint2 y joint3 en el jupyter del taller 5 (mientras que en el taller 4 si está definido).

Agregar estás líneas en: **2. Obtener los manejadores (handlers)**

`# Obtenemos los manejadores para cada una de las articulaciones del robot
ret,joint1=sim.simxGetObjectHandle(clientID,'MTB_joint1',sim.simx_opmode_blocking)
ret,joint2=sim.simxGetObjectHandle(clientID,'MTB_joint2',sim.simx_opmode_blocking)
ret,joint3=sim.simxGetObjectHandle(clientID,'MTB_joint3',sim.simx_opmode_blocking)
`
`print(joint1,joint2,joint3)`

**Y así no tener errores en la parte 3) y 4).**}

Saludos, 
Carlos Bustillo

**Comment by cmoralesd** [comment]
Hola @cabustillo13 
Efectivamente es un error, pero es un error intencional.
Dado que estos son ejercicios en un curso con estudiantes, no incluirlo tiene como propósito que se enfrenten a problemas comunes y que pongan en práctica aquello que han aprendido en las actividades anteriores.
Gracias por comentar y espero los materiales te resulten de utilidad. Saludos!
